### ISSUE TITLE
Initial conditions

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/StructuralIdentifiability.jl#137] opened 2022-12-29 15:34 UTC
How are initial conditions handled?
I can imagine some chemical system where all the initial concentrations are known,
but then only some concentrations are measured during the reaction.
I think identifiability of the reaction kinetics might depend on whether those initial conditions are known or not?
I'm not sure if it is possible to pass that information.

**Comment by pogudingleb** [comment] 2022-12-30 19:51
Right now they are not handled. However, you are completely right, this knowledge may affect the identifiability results. The problem is that the problem with fixed initial condition is quite hard on the theoretical level, to the best of my knowledge there was no sound complete solution. [Here](https://github.com/afvillaverde/strike-goldd/issues/7) is an example of subtlety with other software.

This said, I think the functionality is important enough to implement at least some semi-heuristic methods (with appropriate warnings), I will structure this as a couple of specific separate issues after NY.

**Comment by pogudingleb** [comment] 2023-04-30 20:52
I have elaborated on the problem and possible solutions in #169 and #168

**Closed by pogudingleb** 2023-04-30 20:52 UTC
