### ISSUE TITLE
Dramatically different results from 2 runs

### ISSUE THREAD

**Issue by qchenmath** [SciML/StructuralIdentifiability.jl#98] opened 2022-04-14 12:55 UTC
Did the test twice, and got very different results. Rare events?

Here is the model:
---------------------------------------------------------

using Logging

using StructuralIdentifiability

logger = Logging.SimpleLogger(stdout, Logging.Info)
global_logger(logger)

ode = @ODEmodel(
    S'(t) = -beta_SA * S(t)*(A(t) + P(t) ) - beta_SI *S(t)*In(t),
    E'(t) = beta_SA* S(t) * (A(t) + P(t) ) + beta_SI * S(t)*In(t) - sigma_1*E(t),
    P'(t) = (1-phi)*sigma_1*E(t) - sigma_2*P(t),
    A'(t) =  phi*sigma_1*E(t) - M_ar *A(t),
    In'(t) = sigma_2*P(t) - M*In(t),
    H'(t) = M*In(t) - kappa_s *H(t),
    D'(t) = H(t),
    y(t) = D(t)
)

@time println(assess_identifiability(ode))

1st run:  all are globally identifiable
-----------------------------------------------------
Dict{Any, Symbol}(sigma_2 => :globally, M_ar => :globally, kappa_s => :globally, sigma_1 => :globally, 
beta_SI => :globally, phi => :globally, M => :globally, beta_SA => :globally)
26381.402992 seconds (214.93 M allocations: 13.735 GiB, 0.04% gc time, 0.31% compilation time)

2nd run: took much longer to finish, and only 2 are globally identifiable
-----------------------------------------------------------------------------------------------
Dict{Any, Symbol}(sigma_2 => :locally, M_ar => :globally, kappa_s => :globally, sigma_1 => :locally, 
beta_SI => :locally, phi => :locally, M => :locally, beta_SA => :locally)
67551.049371 seconds (214.83 M allocations: 13.644 GiB, 0.02% gc time, 0.12% compilation time)

**Comment by iliailmer** [comment] 2022-04-15 02:02
I ran one iteration, got what looks like the second result for now. Will do a couple more runs.

**Comment by pogudingleb** [comment] 2022-04-15 06:06
Same here, I also got the second result.

**Comment by pogudingleb** [comment] 2022-04-15 08:04
Ok, I have run the model twice and got the same two results, so something is likely to be wrong, I will check this carefully.

**Comment by iliailmer** [comment] 2022-04-17 01:45
> I ran one iteration, got what looks like the second result for now. Will do a couple more runs.

So far, I keep getting result 2.

**Comment by qchenmath** [comment] 2022-04-19 14:13
> > I ran one iteration, got what looks like the second result for now. Will do a couple more runs.
> 
> So far, I keep getting result 2.

I run it for 6 times in total. Got result 1 twice, and result 2 four times. Also tested other 'smaller' models. All gave expected results. Maybe this model is too complicated in some way -- pushing certain things to its limit?

**Comment by iliailmer** [comment] 2022-04-19 14:40
@qchenmath could you please post the version of StructuralIdentifiability that you are using?

**Comment by pogudingleb** [comment] 2022-04-19 14:45
@qchenmath 
The system is indeed "hard" in an appropriate sense. I have run 10 times (with debugging output to understand the issue) but was not able to get the first result yet, still trying

**Comment by qchenmath** [comment] 2022-04-19 15:16
> @qchenmath The system is indeed "hard" in an appropriate sense. I have run 10 times (with debugging output to understand the issue) but was not able to get the first result yet, still trying

You got the 1st result before?

**Comment by pogudingleb** [comment] 2022-04-19 15:18
> > @qchenmath The system is indeed "hard" in an appropriate sense. I have run 10 times (with debugging output to understand the issue) but was not able to get the first result yet, still trying
> 
> You got the 1st result before?

Yes, but without debuggin output) So I am optimistic that I should get it sooner or later

**Comment by qchenmath** [comment] 2022-04-19 15:20
> @qchenmath could you please post the version of StructuralIdentifiability that you are using?



> @qchenmath could you please post the version of StructuralIdentifiability that you are using?

Status `~/.julia/environments/v1.7/Project.toml`
  [220ca800] StructuralIdentifiability v0.3.8

**Comment by pogudingleb** [comment] 2022-04-20 20:24
@qchenmath 
I managed to reproduce the first behavior and indeed there is a bug in the package we use for Groebner basis computation (likely an overflow) which sometimes shows up for this system. As quick fix for now, the result of GB computation is additionally checked and, if there was such an issue, an error message will appear asking to run the computation again.
This version can be installed now by `Pkg.add(url = "https://github.com/SciML/StructuralIdentifiability.jl")`. I will make a new release ASAP.

More generally, we are considering to switch to a different package for GB computation (https://github.com/SciML/StructuralIdentifiability.jl/pull/77), and this should eliminate this error. I will prioritize this task.

**Comment by qchenmath** [comment] 2022-04-20 21:06
> @qchenmath I managed to reproduce the first behavior and indeed there is a bug in the package we use for Groebner basis computation (likely an overflow) which sometimes shows up for this system. As quick fix for now, the result of GB computation is additionally checked and, if there was such an issue, an error message will appear asking to run the computation again. This version can be installed now by `Pkg.add(url = "https://github.com/SciML/StructuralIdentifiability.jl")`. I will make a new release ASAP.
> 
> More generally, we are considering to switch to a different package for GB computation (#77), and this should eliminate this error. I will prioritize this task.
> 
> Thank you again for reporting the issue carefully!

Thanks a lot. Not sure if it is related. I run it a few more times, and didn't get the 1st result anymore. These runs were on a node with AMD chip.  The earlier runs were on Intel chip. Will try the fix on the Intel chip right away.

**Comment by qchenmath** [comment] 2022-04-24 00:45
Had a couple of more runs - only 2nd result now. 

One related question: Any plan to include the functionality of finding identifiable combinations in the Julia package? I tried the SIAN WebApp. Got the following error message when I tested a complex model:
---------------------------------
Running Multi-Experiment ID check:
---------------------------------
	=> Computing input-output equations
Something went wrong.
Full error message:DifferentialAlgebra:-RosenfeldGroebner, "found functions in 'function' notation, %1, also appearing in 'jet' notation, as in %2", {Ry3(t)}, {Ry3}

Also, tried to use Julia version to find the identifiability of certain combinations:
----------------------------------------------
@time println(assess_identifiability(ode),[Fo*Ro2, Fo+Ro2,Fy*Ry2, Fy+Ry2, (Fo-r1)/Co1, (Fy-r1)/Cy1, 
         (Ro2*Co1 - Fo*Co2 +r1*Co2)/Co1, (Ry2*Cy1-Fy*Cy2 +r1*Cy2)/Cy1])  

Got the error message:

└ @ StructuralIdentifiability /home/xxxx/.julia/packages/StructuralIdentifiability/J6Bol/src/global_identifiability.jl:229
ERROR: LoadError: MethodError: no method matching /(::Nemo.fmpq_mpoly, ::Nemo.fmpq_mpoly)
Closest candidates are:
  /(::Any, !Matched::ChainRulesCore.AbstractThunk) at ~/.julia/packages/ChainRulesCore/RbX5a/src/tangent_types/thunks.jl:33
  /(!Matched::ChainRulesCore.AbstractThunk, ::Any) at ~/.julia/packages/ChainRulesCore/RbX5a/src/tangent_types/thunks.jl:32
  /(!Matched::ChainRulesCore.AbstractZero, ::Any) at ~/.julia/packages/ChainRulesCore/RbX5a/src/tangent_types/abstract_zero.j
l:25

Interesting enough, it finished successfully when I checked all the parameters.


> @qchenmath I managed to reproduce the first behavior and indeed there is a bug in the package we use for Groebner basis computation (likely an overflow) which sometimes shows up for this system. As quick fix for now, the result of GB computation is additionally checked and, if there was such an issue, an error message will appear asking to run the computation again. This version can be installed now by `Pkg.add(url = "https://github.com/SciML/StructuralIdentifiability.jl")`. I will make a new release ASAP.
> 
> More generally, we are considering to switch to a different package for GB computation (#77), and this should eliminate this error. I will prioritize this task.
> 
> Thank you again for reporting the issue carefully!

**Comment by pogudingleb** [comment] 2022-04-24 07:51
@qchenmath 

1. Yes, we plan to include computing identifiable combinations. It is possible now by combining Julia and Maple: the Julia code can find identifiable combination in an non-simplified form, and the one can use https://github.com/pogudingleb/AllIdentifiableFunctions to simplify them. If you have access to Maple, I can write an instruction how to do this (sorry, this is not intuitive for the moment). Otherwise, I can just run it for you.

2. For your example with particular functions to check identifiability,  you should just use `//` for division, so it will be, for example, `(Fo-r1)//Co1` instead `(Fo-r1)/Co1`.

**Comment by iliailmer** [comment] 2022-04-24 13:43
> Something went wrong.
Full error message:DifferentialAlgebra:-RosenfeldGroebner, "found functions in 'function' notation, %1, also appearing in 'jet' notation, as in %2", {Ry3(t)}, {Ry3}

@qchenmath Can you please send the example you used for the webapp?

**Comment by qchenmath** [comment] 2022-04-24 13:50
> > Something went wrong.
> > Full error message:DifferentialAlgebra:-RosenfeldGroebner, "found functions in 'function' notation, %1, also appearing in 'jet' notation, as in %2", {Ry3(t)}, {Ry3}
> 
> @qchenmath Can you please send the example you used for the webapp?

The model:

dPo0/dt = Po1,
dPo1/dt = Po2,
dPo2/dt = -(Fo*Ro2*Ro3*Po0+(Fo*Ro2+Fo*Ro3+Ro2*Ro3)*Po1+(Fo+Ro2+Ro3)*Po2)-alphaO+
gama*(Py3+Fy*Ry2*Ry3*Py0+(Fy*Ry2+Fy*Ry3+Ry2*Ry3)*Py1+(Fy+Ry2+Ry3)*Py2 + alphaY),
dPy0/dt = Py1,
dPy1/dt = Py2,
dPy2/dt = Py3,
dPy3/dt = -(Fy*Ry2*Ry3*Py1+(Fy*Ry2+Fy*Ry3+Ry2*Ry3)*Py2+(Fy+Ry2+Ry3)*Py3) - 
(r1*Py4 +((Cy1+Cy2)*Py2 +(Cy1*(Ry2+Ry3)+Cy2*(Ry3+r1))*Py1 + Ry3*(Cy1*Ry2+r1*Cy2)*Py0 ) +
((Co1+Co2)*Po2 +(Co1*(Ro2+Ro3)+Co2*(Ro3+r1))*Po1 + Ro3*(Co1*Ro2+r1*Co2)*Po0 )-beta)*
(Py3+ Fy*Ry2*Ry3*Py0+(Fy*Ry2+Fy*Ry3+Ry2*Ry3)*Py1+(Fy+Ry2+Ry3)*Py2+ alphaY),
dPy4/dt = -r1*Py4 -((Cy1+Cy2)*Py2 +(Cy1*(Ry2+Ry3)+Cy2*(Ry3+r1))*Py1 + Ry3*(Cy1*Ry2+r1*Cy2)*Py0 )-
((Co1+Co2)*Po2 +(Co1*(Ro2+Ro3)+Co2*(Ro3+r1))*Po1 + Ro3*(Co1*Ro2+r1*Co2)*Po0 ) + beta,
y1 = Po0,
y2 = Py0

You can add the following globally identifiable ones to the output (be sure to add ',' to the line y2=Py0)

y3=alphaO,
y4=alphaY,
y5=Ry3,
y6=Ro3,
y7=r1,
y8=gama

**Comment by qchenmath** [comment] 2022-04-24 13:54
> @qchenmath
> 
>     1. Yes, we plan to include computing identifiable combinations. It is possible now by combining Julia and Maple: the Julia code can find identifiable combination in an non-simplified form, and the one can use https://github.com/pogudingleb/AllIdentifiableFunctions to simplify them. If you have access to Maple, I can write an instruction how to do this (sorry, this is not intuitive for the moment). Otherwise, I can just run it for you.
> 
>     2. For your example with particular functions to check identifiability,  you should just use `//` for division, so it will be, for example, `(Fo-r1)//Co1` instead `(Fo-r1)/Co1`.

Thanks for the tip. It finished, but with the following result:

Dict{Any, Symbol}(alphaO => :globally, Ro2 => :locally, Co2 => :locally, Ry2 => :locally, Ry3 => :globally, Cy1 => :locally, 
alphaY => :globally, r1 => :globally, Fy => :locally, Cy2 => :locally, Co1 => :locally, beta => :nonidentifiable, Fo => :loca
lly, gama => :globally, Ro3 => :globally)AbstractAlgebra.RingElem[Fo*Ro2, Fo + Ro2, Ry2*Fy, Ry2 + Fy, (-r1 + Fo)//Co1, (-r1 +
 Fy)//Cy1, (r1*Co2 - Fo*Co2 + Ro2*Co1)//Co1, (Ry2*Cy1 + Cy2*r1 - Cy2*Fy)//Cy1]

I didn't ask for the identifiability of the individual parameters. It gave the identifiability for those, but not for the combinations I asked for.  We don't have Maple. Here is the model (-the same one in my last post):

ode = @ODEmodel(
    Po0'(t) = Po1(t),
    Po1'(t) = Po2(t),
    Po2'(t) = -(Fo*Ro2*Ro3*Po0(t)+(Fo*Ro2+Fo*Ro3+Ro2*Ro3)*Po1(t)+(Fo+Ro2+Ro3)*Po2(t))-alphaO+gama*(
            Py3+Fy*Ry2*Ry3*Py0(t)+(Fy*Ry2+Fy*Ry3+Ry2*Ry3)*Py1(t)+(Fy+Ry2+Ry3)*Py2(t) +alphaY),
    Py0'(t) = Py1(t),
    Py1'(t) = Py2(t),
    Py2'(t) = Py3(t),
    Py3'(t) = -(Fy*Ry2*Ry3*Py1(t)+(Fy*Ry2+Fy*Ry3+Ry2*Ry3)*Py2(t)+(Fy+Ry2+Ry3)*Py3(t)) - (r1*Py4(t)
                +((Cy1+Cy2)*Py2(t) +(Cy1*(Ry2+Ry3)+Cy2*(Ry3+r1))*Py1(t) + Ry3*(Cy1*Ry2+r1*Cy2)*Py0(t))
                +((Co1+Co2)*Po2(t) +(Co1*(Ro2+Ro3)+Co2*(Ro3+r1))*Po1(t) + Ro3*(Co1*Ro2+r1*Co2)*Po0(t)) -beta)
              *(Py3(t)+ Fy*Ry2*Ry3*Py0(t)+(Fy*Ry2+Fy*Ry3+Ry2*Ry3)*Py1(t)+(Fy+Ry2+Ry3)*Py2(t) + alphaY),
    Py4'(t) = -r1*Py4(t) -((Cy1+Cy2)*Py2(t) +(Cy1*(Ry2+Ry3)+Cy2*(Ry3+r1))*Py1(t) +Ry3*(Cy1*Ry2+r1*Cy2)*Py0(t))
                         -((Co1+Co2)*Po2(t) +(Co1*(Ro2+Ro3)+Co2*(Ro3+r1))*Po1(t) +Ro3*(Co1*Ro2+r1*Co2)*Po0(t)) + beta,
    y1(t) = Po0(t),
    y2(t) = Py0(t)
)

**Comment by pogudingleb** [comment] 2022-04-24 14:26
> > @qchenmath
> > ```
> > 1. Yes, we plan to include computing identifiable combinations. It is possible now by combining Julia and Maple: the Julia code can find identifiable combination in an non-simplified form, and the one can use https://github.com/pogudingleb/AllIdentifiableFunctions to simplify them. If you have access to Maple, I can write an instruction how to do this (sorry, this is not intuitive for the moment). Otherwise, I can just run it for you.
> > 
> > 2. For your example with particular functions to check identifiability,  you should just use `//` for division, so it will be, for example, `(Fo-r1)//Co1` instead `(Fo-r1)/Co1`.
> > ```
> 
> Thanks for the tip. It finished, but with the following result:
> 
> Dict{Any, Symbol}(alphaO => :globally, Ro2 => :locally, Co2 => :locally, Ry2 => :locally, Ry3 => :globally, Cy1 => :locally, alphaY => :globally, r1 => :globally, Fy => :locally, Cy2 => :locally, Co1 => :locally, beta => :nonidentifiable, Fo => :loca lly, gama => :globally, Ro3 => :globally)AbstractAlgebra.RingElem[Fo_Ro2, Fo + Ro2, Ry2_Fy, Ry2 + Fy, (-r1 + Fo)//Co1, (-r1 + Fy)//Cy1, (r1_Co2 - Fo_Co2 + Ro2_Co1)//Co1, (Ry2_Cy1 + Cy2_r1 - Cy2_Fy)//Cy1]
> 
> I didn't ask for the identifiability of the individual parameters. It gave the identifiability for those, but not for the combinations I asked for. We don't have Maple. Here is the model (-the same one in my last post):
> 
> ode = @ODEmodel( Po0'(t) = Po1(t), Po1'(t) = Po2(t), Po2'(t) = -(Fo_Ro2_Ro3_Po0(t)+(Fo_Ro2+Fo_Ro3+Ro2_Ro3)_Po1(t)+(Fo+Ro2+Ro3)_Po2(t))-alphaO+gama_( Py3+Fy_Ry2_Ry3_Py0(t)+(Fy_Ry2+Fy_Ry3+Ry2_Ry3)_Py1(t)+(Fy+Ry2+Ry3)_Py2(t) +alphaY), Py0'(t) = Py1(t), Py1'(t) = Py2(t), Py2'(t) = Py3(t), Py3'(t) = -(Fy_Ry2_Ry3_Py1(t)+(Fy_Ry2+Fy_Ry3+Ry2_Ry3)_Py2(t)+(Fy+Ry2+Ry3)_Py3(t)) - (r1_Py4(t) +((Cy1+Cy2)_Py2(t) +(Cy1_(Ry2+Ry3)+Cy2_(Ry3+r1))_Py1(t) + Ry3_(Cy1_Ry2+r1_Cy2)_Py0(t)) +((Co1+Co2)_Po2(t) +(Co1_(Ro2+Ro3)+Co2_(Ro3+r1))_Po1(t) + Ro3_(Co1_Ro2+r1_Co2)_Po0(t)) -beta) _(Py3(t)+ Fy_Ry2_Ry3_Py0(t)+(Fy_Ry2+Fy_Ry3+Ry2_Ry3)_Py1(t)+(Fy+Ry2+Ry3)_Py2(t) + alphaY), Py4'(t) = -r1_Py4(t) -((Cy1+Cy2)_Py2(t) +(Cy1_(Ry2+Ry3)+Cy2_(Ry3+r1))_Py1(t) +Ry3_(Cy1_Ry2+r1_Cy2)_Py0(t)) -((Co1+Co2)_Po2(t) +(Co1_(Ro2+Ro3)+Co2_(Ro3+r1))_Po1(t) +Ro3_(Co1_Ro2+r1*Co2)*Po0(t)) + beta, y1(t) = Po0(t), y2(t) = Py0(t) )

I believe that the parenthesis have been a bit misplaced, it should rather be
```julia
println(assess_identifiability(ode, [FoRo2, Fo+Ro2,FyRy2, Fy+Ry2, (Fo-r1)/Co1, (Fy-r1)/Cy1,
(Ro2Co1 - FoCo2 +r1Co2)/Co1, (Ry2Cy1-FyCy2 +r1Cy2)/Cy1]))
```

**Comment by qchenmath** [comment] 2022-04-24 14:39
> > > @qchenmath
> > > ```
> > > 1. Yes, we plan to include computing identifiable combinations. It is possible now by combining Julia and Maple: the Julia code can find identifiable combination in an non-simplified form, and the one can use https://github.com/pogudingleb/AllIdentifiableFunctions to simplify them. If you have access to Maple, I can write an instruction how to do this (sorry, this is not intuitive for the moment). Otherwise, I can just run it for you.
> > > 
> > > 2. For your example with particular functions to check identifiability,  you should just use `//` for division, so it will be, for example, `(Fo-r1)//Co1` instead `(Fo-r1)/Co1`.
> > > ```
> > 
> > 
> > Thanks for the tip. It finished, but with the following result:
> > Dict{Any, Symbol}(alphaO => :globally, Ro2 => :locally, Co2 => :locally, Ry2 => :locally, Ry3 => :globally, Cy1 => :locally, alphaY => :globally, r1 => :globally, Fy => :locally, Cy2 => :locally, Co1 => :locally, beta => :nonidentifiable, Fo => :loca lly, gama => :globally, Ro3 => :globally)AbstractAlgebra.RingElem[Fo_Ro2, Fo + Ro2, Ry2_Fy, Ry2 + Fy, (-r1 + Fo)//Co1, (-r1 + Fy)//Cy1, (r1_Co2 - Fo_Co2 + Ro2_Co1)//Co1, (Ry2_Cy1 + Cy2_r1 - Cy2_Fy)//Cy1]
> > I didn't ask for the identifiability of the individual parameters. It gave the identifiability for those, but not for the combinations I asked for. We don't have Maple. Here is the model (-the same one in my last post):
> > ode = @ODEmodel( Po0'(t) = Po1(t), Po1'(t) = Po2(t), Po2'(t) = -(Fo_Ro2_Ro3_Po0(t)+(Fo_Ro2+Fo_Ro3+Ro2_Ro3)_Po1(t)+(Fo+Ro2+Ro3)_Po2(t))-alphaO+gama_( Py3+Fy_Ry2_Ry3_Py0(t)+(Fy_Ry2+Fy_Ry3+Ry2_Ry3)_Py1(t)+(Fy+Ry2+Ry3)_Py2(t) +alphaY), Py0'(t) = Py1(t), Py1'(t) = Py2(t), Py2'(t) = Py3(t), Py3'(t) = -(Fy_Ry2_Ry3_Py1(t)+(Fy_Ry2+Fy_Ry3+Ry2_Ry3)_Py2(t)+(Fy+Ry2+Ry3)_Py3(t)) - (r1_Py4(t) +((Cy1+Cy2)_Py2(t) +(Cy1_(Ry2+Ry3)+Cy2_(Ry3+r1))_Py1(t) + Ry3_(Cy1_Ry2+r1_Cy2)_Py0(t)) +((Co1+Co2)_Po2(t) +(Co1_(Ro2+Ro3)+Co2_(Ro3+r1))_Po1(t) + Ro3_(Co1_Ro2+r1_Co2)_Po0(t)) -beta) _(Py3(t)+ Fy_Ry2_Ry3_Py0(t)+(Fy_Ry2+Fy_Ry3+Ry2_Ry3)_Py1(t)+(Fy+Ry2+Ry3)_Py2(t) + alphaY), Py4'(t) = -r1_Py4(t) -((Cy1+Cy2)_Py2(t) +(Cy1_(Ry2+Ry3)+Cy2_(Ry3+r1))_Py1(t) +Ry3_(Cy1_Ry2+r1_Cy2)_Py0(t)) -((Co1+Co2)_Po2(t) +(Co1_(Ro2+Ro3)+Co2_(Ro3+r1))_Po1(t) +Ro3_(Co1_Ro2+r1*Co2)*Po0(t)) + beta, y1(t) = Po0(t), y2(t) = Py0(t) )
> 
> I believe that the parenthesis have been a bit misplaced, it should rather be
> 
> ```julia
> println(assess_identifiability(ode, [FoRo2, Fo+Ro2,FyRy2, Fy+Ry2, (Fo-r1)/Co1, (Fy-r1)/Cy1,
> (Ro2Co1 - FoCo2 +r1Co2)/Co1, (Ry2Cy1-FyCy2 +r1Cy2)/Cy1]))
> ```

You are right. Interesting, it didn't complain!

**Comment by iliailmer** [comment] 2022-04-24 15:30
> You can add the following globally identifiable ones to the output (be sure to add ',' to the line y2=Py0)
>
>y3=alphaO,
y4=alphaY,
y5=Ry3,
y6=Ro3,
y7=r1,
y8=gama

Going back to the webapp issue, the app considers Ry3 as input function, and not a parameter. For now, the best way to provide globally identifiable parameter known in advance would be to either replace it with a number (@pogudingleb can this affect other parameters if we know the replaced one to be globally identifiable?) or do the following:

1. add dRy3/dt = 0 to ODEs
2. add y5=Ry3

You can also remove `y5`, if the model allows it. Without `y5` the code runs on the webapp

<img width="715" alt="webapp-multi-exp" src="https://user-images.githubusercontent.com/21179258/164984000-19c4268e-7705-4c89-8f61-5b0a08bcfdd5.png">

**Comment by pogudingleb** [comment] 2022-04-24 15:41
@iliailmer 
Yes, replacing a parameter with a constant may make some identifiable combination incorrect, so I would not advise this. 
Another option would be to use SIAN-style input in the app, then `y5 = Ry3` will be interpreted correctly (ie that Ry3 is a parameter).

**Comment by qchenmath** [comment] 2022-04-24 18:28
> @qchenmath
> 
> > You can add the following globally identifiable ones to the output (be sure to add ',' to the line y2=Py0)
> > y3=alphaO,
> > y4=alphaY,
> > y5=Ry3,
> > y6=Ro3,
> > y7=r1,
> > y8=gama
> 
> Going back to the webapp issue, the app considers Ry3 as input function, and not a parameter. For now, the best way to provide globally identifiable parameter known in advance would be to either replace it with a number (@pogudingleb can this affect other parameters if we know the replaced one to be globally identifiable?) or do the following:
> 
>     1. add dRy3/dt = 0 to ODEs
> 
>     2. add y5=Ry3
> 
> 
> You can also remove `y5`, if the model allows it. Without `y5` the code runs on the webapp, this is the result (multi- and single experiment):
> 
> <img alt="webapp-multi-exp" width="715" src="https://user-images.githubusercontent.com/21179258/164984000-19c4268e-7705-4c89-8f61-5b0a08bcfdd5.png">

The results are expected - from my experience with a simpler model. But I tried with and without y5 = Ry3, after adding equ dRy3/dt=0. Neither worked for me.

Also, tried to use SIAN-style. It didn't work either. Here is the model:

diff(Po0(t), t) = Po1(t),
diff(Po1(t), t) = Po2(t),
diff(Po2(t), t) = -(Fo*Ro2*Ro3*Po0(t)+(Fo*Ro2+Fo*Ro3+Ro2*Ro3)*Po1(t)+(Fo+Ro2+Ro3)*Po2(t))-alphaO+gama*(
            Py3+Fy*Ry2*Ry3*Py0(t)+(Fy*Ry2+Fy*Ry3+Ry2*Ry3)*Py1(t)+(Fy+Ry2+Ry3)*Py2(t) +alphaY),
diff(Py0(t), t) = Py1(t),
diff(Py1(t), t) = Py2(t),
diff(Py2(t), t) = Py3(t),
diff(Py3(t), t) = -(Fy*Ry2*Ry3*Py1(t)+(Fy*Ry2+Fy*Ry3+Ry2*Ry3)*Py2(t)+(Fy+Ry2+Ry3)*Py3(t)) - (r1*Py4(t)
                +((Cy1+Cy2)*Py2(t) +(Cy1*(Ry2+Ry3)+Cy2*(Ry3+r1))*Py1(t) + Ry3*(Cy1*Ry2+r1*Cy2)*Py0(t))
                +((Co1+Co2)*Po2(t) +(Co1*(Ro2+Ro3)+Co2*(Ro3+r1))*Po1(t) + Ro3*(Co1*Ro2+r1*Co2)*Po0(t)) -beta)
              *(Py3(t)+ Fy*Ry2*Ry3*Py0(t)+(Fy*Ry2+Fy*Ry3+Ry2*Ry3)*Py1(t)+(Fy+Ry2+Ry3)*Py2(t) + alphaY),
diff(Py4(t), t) = -r1*Py4(t) -((Cy1+Cy2)*Py2(t) +(Cy1*(Ry2+Ry3)+Cy2*(Ry3+r1))*Py1(t) +Ry3*(Cy1*Ry2+r1*Cy2)*Py0(t))
                         -((Co1+Co2)*Po2(t) +(Co1*(Ro2+Ro3)+Co2*(Ro3+r1))*Po1(t) +Ro3*(Co1*Ro2+r1*Co2)*Po0(t)) + beta,
y1(t) = Po0(t),
y2(t) = Py0(t),
y3(t)=alphaO,
y4(t)=alphaY,
y5(t)=Ry3,
y6(t)=Ro3,
y7(t)=r1,
y8(t)=gama


Error message: 

---------------------------------
Running Multi-Experiment ID check:
---------------------------------
	=> Computing input-output equations

  Something went wrong.
Full error message:DifferentialAlgebra:-DifferentialRing, "found the dependent variable(s): 
%1, ranked in 'blocks = %2' after the arbitrary variable(s) %3. That would imply that the 
variable(s) %1 are also arbitrary. Please re-enter with 'blocks = ...' free of this ambiguity.", 
"Py4, y1, y2, y3, y4, y5, y6, y7, y8", [[Po0, Po1, Po2, Py0, Py1, Py2, Py3, Py4], 
[y1, y2, y3, y4, y5, y6, y7, y8]], Py3

**Comment by iliailmer** [comment] 2022-04-25 01:47
@qchenmath There is a `Py3(t)` missing in the 3rd ODE:

diff(Po2(t), t) = -(FoRo2Ro3Po0(t)+(FoRo2+FoRo3+Ro2Ro3)Po1(t)+(Fo+Ro2+Ro3)Po2(t))-alphaO+gama(
**Py3**+FyRy2Ry3Py0(t)+(FyRy2+FyRy3+Ry2Ry3)Py1(t)+(Fy+Ry2+Ry3)Py2(t) +alphaY)

This should be the reason why the app complains.

**Comment by qchenmath** [comment] 2022-04-25 02:33
> @qchenmath There is a `Py3(t)` missing in the 3rd ODE:
> 
> diff(Po2(t), t) = -(FoRo2Ro3Po0(t)+(FoRo2+FoRo3+Ro2Ro3)Po1(t)+(Fo+Ro2+Ro3)Po2(t))-alphaO+gama( **Py3**+FyRy2Ry3Py0(t)+(FyRy2+FyRy3+Ry2Ry3)Py1(t)+(Fy+Ry2+Ry3)Py2(t) +alphaY)
> 
> This should be the reason why the app complains:
> 
> <img alt="multi-exp-2" width="713" src="https://user-images.githubusercontent.com/21179258/165008039-81aec915-403a-484d-9377-73f16ae65feb.png">

Thanks a lot. Didn't expect myself to make such a mistake. Now it works fine with SIAN-style input.

**Comment by pogudingleb** [comment] 2022-07-12 12:29
@qchenmath 
For your original question: the new release 0.4.0 of `StructuralIdentifiability` uses another backend for Groebner bases, so now one gets always the second result (which is correct) and, by the way, faster. Let us know if you will have any questions/comments.

**Closed by pogudingleb** 2022-07-12 12:29 UTC
